# Generated by Django 6.0.4 on 2026-06-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cote', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together=set(),
        ),
    ]
